# 使用 Node.js 作为基础镜像
FROM node:16

# 设置工作目录
WORKDIR /app

# 设置 npm 镜像源
RUN npm config set registry https://registry.npmmirror.com

# 复制 package.json 和 package-lock.json
COPY package*.json ./

# 安装依赖
RUN npm install

# 复制项目文件
COPY . .

# 添加执行权限
RUN chmod +x ./node_modules/.bin/*

# 暴露应用程序端口
EXPOSE 3007

# 启动应用程序
CMD ["node", "app.js"]